---

gitlab_version: "16.6.1"
gitlab_edition: community # [ community | enterprise ]

gitlab_external_fqdn: ""
# Note: if you specify anything else than 443 for 'external_port', the
#       provisioning of the Let's Encrypt certificate will fail.
gitlab_external_port: 443
