---

# See the documented procedure:
# <https://docs.gitlab.com/omnibus/installation/#uninstall-the-linux-package-omnibus>

- name: GitLab | is completely uninstalled
  hosts: gitlab
  vars:
    gitlab_destroy_data: true
  tasks:
    - name: GitLab uninstall | processes are stopped, accounts removed
      become: true
      ansible.builtin.command:
        cmd: gitlab-ctl {{ command }}
      loop_control:
        loop_var: command
        pause: 5
      loop:
        - stop
        - remove-accounts
      tags: [ stop-processes ]

    - name: GitLab uninstall | runsvdir is stopped
      become: true
      ansible.builtin.systemd_service:
        name: gitlab-runsvdir
        enabled: false
        state: stopped
      tags: [ stop-process-supervisor ]

    - name: GitLab uninstall | the 'gitlab-runsvdir' unit file is absent
      become: true
      ansible.builtin.file:
        path: /usr/lib/systemd/system/gitlab-runsvdir.service
        state: absent
      tags: [ remove-unit-file ]

    - name: GitLab uninstall | the systemd daemon is reloaded
      become: true
      ansible.builtin.systemd_service:
        daemon_reload: true
      tags: [ reload-systemd ]

    - name: GitLab uninstall | the "failed" state of all systemd units is reset
      become: true
      ansible.builtin.command:
        cmd: systemctl reset-failed
      tags: [ reset-systemd-unit-failed-state ]

    - name: GitLab uninstall | the process supervisor is uninstalled
      become: true
      ansible.builtin.command:
        cmd: gitlab-ctl uninstall
      tags: [ uninstall-process-supervisor ]

    - name: GitLab uninstall | data is destroyed
      when: gitlab_destroy_data | default(false) | bool
      block:
        - name: GitLab uninstall | all gitlab data is deleted
          become: true
          ansible.builtin.command: gitlab-ctl cleanse

        - name: GitLab uninstall | the base directory is removed
          become: true
          ansible.builtin.file:
            path: /opt/gitlab
            state: absent
      tags: [ destroy-data ]

    - name: GitLab uninstall | the all-in-one package is removed
      become: true
      ansible.builtin.package:
        name: gitlab-ce
        state: absent
      tags: [ uninstall-package ]
